-- Core agency-operability controls.
-- Apply after abandoned_offer_lifecycle_v1.sql.

alter table public.creators
    add column if not exists vault_initial_categorized_at timestamptz null,
    add column if not exists auto_categorize_new_media boolean not null default true,
    add column if not exists auto_audience_policy jsonb not null default '{"scope":"all","match_mode":"any","include_list_ids":[],"exclude_list_ids":[],"spend_tiers":[],"include_new_fans":false}'::jsonb,
    add column if not exists last_chat_reconcile_at timestamptz null;

create or replace function public.claim_chat_reconciliation(
    p_creator_id uuid,
    p_min_interval_minutes integer default 10
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
    v_claimed uuid;
begin
    update public.creators
       set last_chat_reconcile_at = now()
     where id = p_creator_id
       and (
           last_chat_reconcile_at is null
           or last_chat_reconcile_at <= now() - make_interval(mins => greatest(p_min_interval_minutes, 1))
       )
    returning id into v_claimed;
    return v_claimed is not null;
end;
$$;

alter table public.creator_commercial_policies
    add column if not exists require_operator_ppv_approval boolean not null default false;

create table if not exists public.ppv_approval_requests (
    id uuid primary key default gen_random_uuid(),
    creator_id uuid not null references public.creators(id) on delete cascade,
    fan_id uuid not null references public.fans(id) on delete cascade,
    status text not null default 'pending'
        check (status in ('pending', 'sending', 'sent', 'rejected', 'cancelled', 'failed')),
    source text not null default 'auto',
    message_content text not null default '',
    media_ids jsonb not null default '[]'::jsonb,
    price_cents integer not null check (price_cents > 0),
    set_id text null,
    step_index integer null,
    approved_experience text null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    resolved_at timestamptz null,
    resolved_by uuid null,
    last_error text null
);

create unique index if not exists ppv_approval_requests_one_pending_per_fan_idx
    on public.ppv_approval_requests (fan_id)
    where status in ('pending', 'sending');

create index if not exists ppv_approval_requests_creator_status_created_idx
    on public.ppv_approval_requests (creator_id, status, created_at desc);

alter table public.ppv_approval_requests enable row level security;

create table if not exists public.vault_recategorization_events (
    id bigint generated by default as identity primary key,
    creator_id uuid not null references public.creators(id) on delete cascade,
    media_id text not null,
    created_at timestamptz not null default now()
);

create index if not exists vault_recategorization_events_creator_created_idx
    on public.vault_recategorization_events (creator_id, created_at desc);

alter table public.vault_recategorization_events enable row level security;

-- Claims one of the creator's daily manual AI re-analysis slots atomically.
-- The advisory lock prevents simultaneous dashboard requests from exceeding
-- the limit. The UTC-day boundary makes the rule deterministic across workers.
create or replace function public.claim_vault_recategorization(
    p_creator_id uuid,
    p_media_id text,
    p_daily_limit integer default 5
)
returns table (used integer, remaining integer)
language plpgsql
security definer
set search_path = public
as $$
declare
    v_used integer;
begin
    perform pg_advisory_xact_lock(hashtext(p_creator_id::text));

    select count(*)::integer
      into v_used
      from public.vault_recategorization_events
     where creator_id = p_creator_id
       and created_at >= date_trunc('day', now() at time zone 'UTC') at time zone 'UTC';

    if v_used >= p_daily_limit then
        raise exception 'daily vault re-categorization limit reached'
            using errcode = 'P0001';
    end if;

    insert into public.vault_recategorization_events (creator_id, media_id)
    values (p_creator_id, p_media_id);

    v_used := v_used + 1;
    return query select v_used, greatest(p_daily_limit - v_used, 0);
end;
$$;

create or replace function public.vault_recategorization_usage(
    p_creator_id uuid,
    p_daily_limit integer default 5
)
returns table (used integer, remaining integer, daily_limit integer)
language sql
stable
security definer
set search_path = public
as $$
    with usage as (
        select count(*)::integer as used
          from public.vault_recategorization_events
         where creator_id = p_creator_id
           and created_at >= date_trunc('day', now() at time zone 'UTC') at time zone 'UTC'
    )
    select used, greatest(p_daily_limit - used, 0), p_daily_limit
      from usage;
$$;

-- These mutation/usage functions are backend-only. The dashboard reaches them
-- through the authenticated API; browser Supabase roles cannot claim quotas or
-- reconciliation leases directly.
revoke all on function public.claim_chat_reconciliation(uuid, integer)
    from public, anon, authenticated;
revoke all on function public.claim_vault_recategorization(uuid, text, integer)
    from public, anon, authenticated;
revoke all on function public.vault_recategorization_usage(uuid, integer)
    from public, anon, authenticated;

grant execute on function public.claim_chat_reconciliation(uuid, integer) to service_role;
grant execute on function public.claim_vault_recategorization(uuid, text, integer) to service_role;
grant execute on function public.vault_recategorization_usage(uuid, integer) to service_role;
